name: mokkon_cards
description: Mokkon Cards
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  cloud_firestore:
  firebase_core:
  firebase_auth: ^0.11.1+6
  uuid: 2.0.0
  pin_code_text_field: ^1.3.6
  provider: ^2.0.0+1
  qr_flutter: ^2.1.0+55
dev_dependencies:
  flutter_launcher_icons: "^0.7.2"
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/m.jpg
   - assets/mlogo.png
   - assets/john.jpg
   - assets/icons/icon.png
   - assets/icons/gender.png
   - assets/icons/password.png

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icons/icon.png"